version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into DockerHub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - echo Cloning env file from GitHub...
      - git clone https://github.com/YOUR-USERNAME/YOUR-REPO.git temp-repo
      - cp temp-repo/build-args.env .
  build:
    commands:
      - echo Loading build arguments...
      - set -a
      - source build-args.env
      - set +a
      - BUILD_ARGS=""
      - for var in $(cut -d= -f1 build-args.env); do
          BUILD_ARGS="$BUILD_ARGS --build-arg $var=${!var}";
        done
      - echo Building Docker image...
      - docker build $BUILD_ARGS -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing Docker image to DockerHub...
      - docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
